# INFY Custom Data Source (DB-backed)
This notebook loads INFY daily bars from Postgres via a custom QuantConnect `PythonData` source.

In [1]:
# QuantBook Analysis Tool
qb = QuantBook()

# Force reload so notebook always uses latest db_tick_custom_data.py on disk
import importlib
import db_tick_custom_data
importlib.reload(db_tick_custom_data)
print("db_tick_custom_data loaded from:", db_tick_custom_data.__file__)

DbDailyByTradingsymbol = db_tick_custom_data.DbDailyByTradingsymbol

original_log = DbDailyByTradingsymbol._log.__func__
@classmethod
def quiet_cache_hit_log(cls, message: str) -> None:
    if str(message).startswith("Using existing cache for "):
        return
    return original_log(cls, message)

DbDailyByTradingsymbol._log = quiet_cache_hit_log

db_tick_custom_data loaded from: /Lean/Launcher/bin/Debug/Notebooks/db_tick_custom_data.py

In [18]:
# Request INFY data through custom data subscription
qb.set_start_date(2026, 4, 22)
infy_custom = qb.add_data(DbDailyByTradingsymbol, "INFY", Resolution.DAILY)

# Get 360 daily bars, similar to Cell 2 style
history = qb.history(infy_custom.symbol, 360, Resolution.DAILY)
history.tail()

[DbDailyByTradingsymbol] Refreshing cache for INFY
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=INFY
[DbDailyByTradingsymbol] Resolved instrument_token=408065
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1154.8/41354744 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/INFY.csv

                                         close    high     low    open  \
symbol                      time
INFY.DbDailyByTradingsymbol 2026-04-16  1319.2  1331.0  1309.0  1322.1
                            2026-04-17  1318.7  1328.3  1306.1  1313.0
                            2026-04-20  1312.6  1324.9  1308.1  1320.0
                            2026-04-21  1313.2  1325.0  1299.3  1310.0
                            2026-04-22  1257.9  1297.7  1257.0  1295.0

                                         value      volume
symbol                      time
INFY.DbDailyByTradingsymbol 2026-04-16  1319.2  18527029.0
                            2026-04-17  1318.7  12064048.0
                            2026-04-20  1312.6   7172300.0
                            2026-04-21  1313.2  10057440.0
                            2026-04-22  1257.9  10635696.0

## Universe from sector-tree + index-constituents

This section builds a custom universe by intersecting:
- Sector subtree for `IT Services` (from `sector-tree`)
- Constituents of `BSE 1000` (from `index-constituents`)

The output universe is a list of NSE codes.

In [31]:
# Initialize universe from db_universe_custom_data and simulate 3-year selector behavior

import importlib
from datetime import datetime, timedelta

import pandas as pd

import db_universe_custom_data
import utils

importlib.reload(db_universe_custom_data)
importlib.reload(utils)

# === Load real universe payload from DB ===
print("Loading universe payload from DB...")
session_local = db_universe_custom_data.build_session_local()
payload = db_universe_custom_data.build_universe_payload(session_local)
universe_list = payload.get("universe", [])

if not universe_list:
    raise RuntimeError("DB universe payload is empty.")

print(f"Loaded {len(universe_list)} symbols from DB")

Loading universe payload from DB...
Loaded 58 symbols from DB

In [42]:
# Top-10 by Market Cap for all timestamps
universe_lookup = {row["nse_code"]: row for row in universe_list}

market_cap_by_code = {}
for code, row in universe_lookup.items():
    series = utils.extract_metric_series(
        row.get("processed_financial_data", {}),
        utils.FINANCIAL_SCORE_SECTION,
        utils.FINANCIAL_SCORE_ROW,
    )
    market_cap_by_code[code] = series if series is not None else pd.Series(dtype=float)

market_cap_matrix = pd.DataFrame.from_dict(market_cap_by_code, orient="index")
market_cap_matrix = market_cap_matrix.dropna(axis=1, how="all")

timestamps = pd.to_datetime(market_cap_matrix.columns, errors="coerce")
market_cap_matrix = market_cap_matrix.loc[:, timestamps.notna()]
market_cap_matrix.columns = timestamps[timestamps.notna()]
market_cap_matrix = market_cap_matrix.sort_index(axis=1)

if market_cap_matrix.empty:
    raise RuntimeError("No Market Cap data")

subscribed_symbols = []

for ts in market_cap_matrix.columns:
    ranked = market_cap_matrix[ts].dropna().nlargest(10)

    for symbol in active_subscription_symbols:
        qb.remove_security(symbol)

    active_subscription_symbols = []
    subscribed_symbols = []

    for code, cap in ranked.items():
        security = qb.add_data(DbDailyByTradingsymbol, code, Resolution.DAILY)
        active_subscription_symbols.append(security.symbol)
        subscribed_symbols.append(
            {
                "nse_code": code,
                "symbol": security.symbol,
                "market_cap": float(cap),
            }
        )

    print(str(ts), [(item["nse_code"], item["market_cap"]) for item in subscribed_symbols])

2001-04-01 00:00:00 [('RELIANCE', 42484.2)]
2001-05-01 00:00:00 [('RELIANCE', 48708.0)]
2001-06-01 00:00:00 [('RELIANCE', 45731.4)]
2001-07-01 00:00:00 [('RELIANCE', 39575.25)]
2001-08-01 00:00:00 [('RELIANCE', 38628.15)]
2001-09-01 00:00:00 [('RELIANCE', 32877.9)]
2001-10-01 00:00:00 [('RELIANCE', 31592.55)]
2001-11-01 00:00:00 [('RELIANCE', 35989.8)]
2001-12-01 00:00:00 [('RELIANCE', 38019.3)]
2002-01-01 00:00:00 [('RELIANCE', 37207.5)]
2002-02-01 00:00:00 [('RELIANCE', 38222.25)]
2002-03-01 00:00:00 [('RELIANCE', 37275.15)]
2002-04-01 00:00:00 [('RELIANCE', 34501.5)]
2002-05-01 00:00:00 [('RELIANCE', 32742.6)]
2002-06-01 00:00:00 [('RELIANCE', 33419.1)]
2002-07-01 00:00:00 [('RELIANCE', 30307.2)]
2002-08-01 00:00:00 [('RELIANCE', 31727.85)]
2002-09-01 00:00:00 [('RELIANCE', 32066.1)]
2002-10-01 00:00:00 [('RELIANCE', 32945.55)]
2002-11-01 00:00:00 [('RELIANCE', 35719.2)]
2002-12-01 00:00:00 [('RELIANCE', 37004.55)]
2003-01-01 00:00:00 [('RELIANCE', 34095.6), ('INFY', 27279.14), ('WIPRO', 23287.8), ('ICICIBANK', 19538.25), ('HDFCBANK', 18160.2), ('BANKINDIA', 16357.25), ('ITC', 14973.35), ('HINDALCO', 11515.5), ('BHARTIARTL', 8312.85), ('DRREDDY', 7544.22)]
2003-02-01 00:00:00 [('RELIANCE', 36598.65), ('INFY', 27185.76), ('WIPRO', 24389.25), ('ICICIBANK', 19466.55), ('HDFCBANK', 19237.5), ('BANKINDIA', 15697.5), ('ITC', 15286.6), ('HINDALCO', 11272.5), ('BHARTIARTL', 8191.05), ('DRREDDY', 7318.78)]
2003-03-01 00:00:00 [('RELIANCE', 34501.5), ('INFY', 25711.98), ('WIPRO', 20455.5), ('HDFCBANK', 18006.3), ('ICICIBANK', 17437.44), ('BANKINDIA', 16662.1), ('ITC', 14722.75), ('HINDALCO', 10262.25), ('BHARTIARTL', 8434.65), ('DRREDDY', 7652.78)]
2003-04-01 00:00:00 [('RELIANCE', 34095.6), ('HDFCBANK', 19083.6), ('BANKINDIA', 18573.1), ('INFY', 17677.24), ('ITC', 16038.4), ('ICICIBANK', 15795.51), ('WIPRO', 14318.85), ('HINDALCO', 11830.5), ('BHARTIARTL', 10109.4), ('DRREDDY', 7285.38)]
2003-05-01 00:00:00 [('RELIANCE', 37072.2), ('BANKINDIA', 24083.15), ('HDFCBANK', 18775.8), ('ICICIBANK', 17982.36), ('INFY', 16966.74), ('ITC', 16289.0), ('WIPRO', 13322.3), ('HINDALCO', 13115.25), ('BHARTIARTL', 11388.3), ('DRREDDY', 7439.85)]
2003-06-01 00:00:00 [('RELIANCE', 40319.4), ('BANKINDIA', 22877.4), ('INFY', 20770.96), ('HDFCBANK', 19853.1), ('ICICIBANK', 19574.1), ('ITC', 17980.55), ('WIPRO', 15682.55), ('HINDALCO', 14343.75), ('BHARTIARTL', 11662.35), ('DRREDDY', 9130.73)]
2003-07-01 00:00:00 [('RELIANCE', 44446.05), ('INFY', 22853.74), ('BANKINDIA', 21644.35), ('ICICIBANK', 20749.98), ('HDFCBANK', 20468.7), ('ITC', 16790.2), ('HINDALCO', 15702.75), ('WIPRO', 15682.55), ('BHARTIARTL', 15133.65), ('TATASTEEL', 10545.6)]
2003-08-01 00:00:00 [('RELIANCE', 49722.75), ('INFY', 24904.04), ('BANKINDIA', 23600.85), ('ICICIBANK', 23424.39), ('HDFCBANK', 21238.2), ('BHARTIARTL', 20706.0), ('ITC', 19484.15), ('WIPRO', 17675.65), ('HINDALCO', 17509.5), ('TATASTEEL', 13777.92)]
2003-09-01 00:00:00 [('RELIANCE', 55067.1), ('INFY', 28724.5), ('ICICIBANK', 26658.06), ('BANKINDIA', 23905.7), ('BHARTIARTL', 23751.0), ('HDFCBANK', 21238.2), ('WIPRO', 20822.65), ('ITC', 18795.0), ('HINDALCO', 17660.25), ('TATASTEEL', 15125.76)]
2003-10-01 00:00:00 [('RELIANCE', 60343.8), ('ICICIBANK', 32200.47), ('INFY', 30060.24), ('BANKINDIA', 27268.15), ('BHARTIARTL', 27009.15), ('HDFCBANK', 24316.2), ('WIPRO', 22238.8), ('TATASTEEL', 21340.8), ('HINDALCO', 21084.75), ('ITC', 20298.6)]
2003-11-01 00:00:00 [('RELIANCE', 60479.1), ('ICICIBANK', 32601.99), ('INFY', 31249.82), ('WIPRO', 25438.25), ('BHARTIARTL', 25334.4), ('BANKINDIA', 24806.6), ('HINDALCO', 23784.75), ('HDFCBANK', 23238.9), ('TATASTEEL', 21528.0), ('ITC', 20110.65)]
2003-12-01 00:00:00 [('RELIANCE', 71100.15), ('ICICIBANK', 38517.24), ('INFY', 35301.7), ('BHARTIARTL', 31424.4), ('BANKINDIA', 28978.95), ('WIPRO', 28795.05), ('HDFCBANK', 28009.8), ('TATASTEEL', 27443.52), ('HINDALCO', 27024.75), ('ITC', 23055.2)]
2004-01-01 00:00:00 [('RELIANCE', 69544.2), ('BHARTIARTL', 40254.9), ('ICICIBANK', 38467.05), ('INFY', 33068.7), ('BANKINDIA', 28319.2), ('HDFCBANK', 26470.8), ('WIPRO', 25805.4), ('TATASTEEL', 24822.72), ('ITC', 24057.6), ('HINDALCO', 22290.75)]
2004-02-01 00:00:00 [('RELIANCE', 68867.7), ('BHARTIARTL', 42569.1), ('ICICIBANK', 35319.42), ('INFY', 32114.6), ('HDFCBANK', 28779.3), ('BANKINDIA', 27027.0), ('TATASTEEL', 26345.28), ('ITC', 25811.8), ('WIPRO', 24074.55), ('HINDALCO', 23917.5)]
2004-03-01 00:00:00 [('RELIANCE', 66770.55), ('BHARTIARTL', 46558.05), ('ICICIBANK', 38624.79), ('INFY', 31326.96), ('HDFCBANK', 29087.1), ('BANKINDIA', 25862.2), ('ITC', 24496.15), ('HINDALCO', 23424.75), ('TATASTEEL', 23175.36), ('WIPRO', 22553.5)]
2004-04-01 00:00:00 [('RELIANCE', 65349.9), ('BHARTIARTL', 50760.15), ('ICICIBANK', 41062.59), ('INFY', 32646.46), ('BANKINDIA', 31153.85), ('HDFCBANK', 29087.1), ('WIPRO', 25543.15), ('ITC', 25310.6), ('HINDALCO', 21390.75), ('TATASTEEL', 21340.8)]
2004-05-01 00:00:00 [('RELIANCE', 53308.2), ('BHARTIARTL', 44213.4), ('ICICIBANK', 34824.69), ('INFY', 31148.32), ('BANKINDIA', 28537.6), ('HDFCBANK', 27855.9), ('WIPRO', 25018.65), ('ITC', 21050.4), ('TATASTEEL', 19206.72), ('HINDALCO', 17703.0)]
2004-06-01 00:00:00 [('RELIANCE', 53308.2), ('BHARTIARTL', 40803.0), ('INFY', 35045.92), ('ICICIBANK', 31870.65), ('HDFCBANK', 28471.5), ('WIPRO', 26434.8), ('ITC', 20799.8), ('BANKINDIA', 20525.05), ('HINDALCO', 19134.0), ('TATASTEEL', 17259.84)]
2004-07-01 00:00:00 [('RELIANCE', 60682.05), ('BHARTIARTL', 45522.75), ('INFY', 39422.6), ('ICICIBANK', 34874.88), ('HDFCBANK', 28933.2), ('WIPRO', 27169.1), ('ITC', 24370.85), ('TATASTEEL', 23786.88), ('HINDALCO', 21147.75), ('BANKINDIA', 21052.85)]
2004-08-01 00:00:00 [('RELIANCE', 58990.8), ('BHARTIARTL', 41807.85), ('INFY', 39978.82), ('ICICIBANK', 35168.85), ('WIPRO', 28742.6), ('HDFCBANK', 28317.6), ('ITC', 24558.8), ('TATASTEEL', 22738.56), ('HINDALCO', 22621.5), ('BANKINDIA', 20065.5)]
2004-09-01 00:00:00 [('RELIANCE', 64267.5), ('BHARTIARTL', 43726.2), ('INFY', 43023.82), ('ICICIBANK', 37319.85), ('HDFCBANK', 30933.9), ('WIPRO', 29634.25), ('TATASTEEL', 26769.6), ('ITC', 26688.9), ('HINDALCO', 26030.25), ('BANKINDIA', 22568.0)]
2004-10-01 00:00:00 [('RELIANCE', 65688.15), ('INFY', 48374.9), ('BHARTIARTL', 46984.35), ('ICICIBANK', 38983.29), ('WIPRO', 32676.35), ('HDFCBANK', 32011.2), ('TATASTEEL', 26644.8), ('ITC', 25498.55), ('HINDALCO', 22788.0), ('BANKINDIA', 22349.6)]
2004-11-01 00:00:00 [('RELIANCE', 64132.2), ('NTPC', 58772.3), ('INFY', 54537.98), ('BHARTIARTL', 51917.25), ('ICICIBANK', 44289.09), ('HDFCBANK', 38167.2), ('WIPRO', 38078.7), ('BANKINDIA', 33151.3), ('TATASTEEL', 30488.64), ('ITC', 30259.95)]
2004-12-01 00:00:00 [('RELIANCE', 66297.0), ('NTPC', 64825.1), ('BHARTIARTL', 64675.8), ('INFY', 53076.38), ('ICICIBANK', 48411.84), ('BANKINDIA', 41405.0), ('HDFCBANK', 40014.0), ('WIPRO', 37239.5), ('TATASTEEL', 37140.48), ('ITC', 30761.15)]
2005-01-01 00:00:00 [('BHARTIARTL', 68908.35), ('RELIANCE', 66026.4), ('NTPC', 64272.2), ('INFY', 52491.74), ('ICICIBANK', 47049.54), ('HDFCBANK', 43399.8), ('TATASTEEL', 37252.8), ('BANKINDIA', 37100.7), ('WIPRO', 35036.6), ('ITC', 31888.85)]
2005-02-01 00:00:00 [('NTPC', 69102.8), ('RELIANCE', 69003.0), ('BHARTIARTL', 67294.5), ('INFY', 56844.06), ('ICICIBANK', 49652.25), ('HDFCBANK', 45246.6), ('TATASTEEL', 41096.64), ('BANKINDIA', 39011.7), ('WIPRO', 34721.9), ('ITC', 30385.25)]
2005-03-01 00:00:00 [('RELIANCE', 67785.3), ('NTPC', 63379.8), ('BHARTIARTL', 61996.2), ('INFY', 57278.48), ('ICICIBANK', 51208.14), ('BANKINDIA', 45509.1), ('HDFCBANK', 41860.8), ('TATASTEEL', 38837.76), ('WIPRO', 33358.2), ('ITC', 31450.3)]
2005-04-01 00:00:00 [('RELIANCE', 65552.85), ('BHARTIARTL', 61691.7), ('NTPC', 61042.1), ('INFY', 47879.58), ('ICICIBANK', 46927.65), ('HDFCBANK', 41245.2), ('BANKINDIA', 35958.65), ('ITC', 33768.35), ('TATASTEEL', 32373.12), ('WIPRO', 31365.1)]
2005-05-01 00:00:00 [('BHARTIARTL', 66929.1), ('RELIANCE', 66432.3), ('NTPC', 62050.9), ('INFY', 57107.96), ('ICICIBANK', 51107.76), ('BANKINDIA', 44458.05), ('HDFCBANK', 41553.0), ('ITC', 37464.7), ('WIPRO', 35561.1), ('TATASTEEL', 34756.8)]
2005-06-01 00:00:00 [('RELIANCE', 79759.35), ('BHARTIARTL', 72653.7), ('NTPC', 61672.6), ('INFY', 59840.34), ('ICICIBANK', 55502.97), ('HDFCBANK', 48940.2), ('BANKINDIA', 45445.4), ('ITC', 38968.3), ('WIPRO', 38078.7), ('TATASTEEL', 32198.4)]
2005-07-01 00:00:00 [('RELIANCE', 87268.5), ('BHARTIARTL', 84620.55), ('NTPC', 69694.5), ('ICICIBANK', 69670.89), ('BANKINDIA', 62589.8), ('INFY', 57562.68), ('HDFCBANK', 53865.0), ('ITC', 39469.5), ('WIPRO', 36610.1), ('TATASTEEL', 35243.52)]
2005-08-01 00:00:00 [('BHARTIARTL', 94212.3), ('RELIANCE', 89298.0), ('NTPC', 75834.6), ('ICICIBANK', 62809.2), ('INFY', 60295.06), ('BANKINDIA', 52183.95), ('HDFCBANK', 49248.0), ('ITC', 40597.2), ('TATASTEEL', 37689.6), ('WIPRO', 36242.95)]
2005-09-01 00:00:00 [('BHARTIARTL', 104260.8), ('RELIANCE', 98498.4), ('NTPC', 78725.2), ('ICICIBANK', 78439.8), ('INFY', 63827.26), ('BANKINDIA', 53963.0), ('HDFCBANK', 52633.8), ('ITC', 48115.2), ('TATASTEEL', 41221.44), ('WIPRO', 36924.8)]
2005-10-01 00:00:00 [('BHARTIARTL', 96465.6), ('RELIANCE', 94642.35), ('NTPC', 72187.4), ('ICICIBANK', 64996.05), ('INFY', 63993.72), ('BANKINDIA', 46978.75), ('HDFCBANK', 46631.7), ('ITC', 42288.75), ('WIPRO', 36242.95), ('TATASTEEL', 32198.4)]
2005-11-01 00:00:00 [('BHARTIARTL', 106696.8), ('RELIANCE', 103369.2), ('NTPC', 77464.2), ('ICICIBANK', 70144.11), ('INFY', 68118.68), ('HDFCBANK', 52941.6), ('BANKINDIA', 48648.6), ('ITC', 47300.75), ('WIPRO', 42064.9), ('TATASTEEL', 33296.64)]
2005-12-01 00:00:00 [('RELIANCE', 110404.8), ('BHARTIARTL', 103255.95), ('NTPC', 83216.3), ('ICICIBANK', 76267.29), ('INFY', 76047.86), ('BANKINDIA', 55719.3), ('HDFCBANK', 54480.6), ('ITC', 49994.7), ('WIPRO', 45998.65), ('TATASTEEL', 36591.36)]
2006-01-01 00:00:00 [('RELIANCE', 115140.3), ('BHARTIARTL', 106788.15), ('NTPC', 85078.7), ('ICICIBANK', 79422.09), ('INFY', 73088.12), ('HDFCBANK', 58635.9), ('BANKINDIA', 57011.5), ('ITC', 54505.5), ('WIPRO', 52659.8), ('TATASTEEL', 39212.16)]
2006-02-01 00:00:00 [('RELIANCE', 114260.85), ('BHARTIARTL', 107914.8), ('NTPC', 97455.9), ('ICICIBANK', 80203.62), ('INFY', 71784.86), ('ITC', 60707.85), ('BANKINDIA', 58945.25), ('HDFCBANK', 56635.2), ('WIPRO', 51768.15), ('TATASTEEL', 42070.08)]
2006-03-01 00:00:00 [('RELIANCE', 128264.4), ('BHARTIARTL', 123383.4), ('NTPC', 99648.1), ('ICICIBANK', 76790.7), ('INFY', 75654.04), ('ITC', 68664.4), ('HDFCBANK', 59559.3), ('BANKINDIA', 58635.85), ('WIPRO', 55649.45), ('TATASTEEL', 53414.4)]
2006-04-01 00:00:00 [('RELIANCE', 164930.7), ('BHARTIARTL', 121251.9), ('NTPC', 100909.1), ('INFY', 79669.38), ('ICICIBANK', 75191.79), ('ITC', 70669.2), ('TATASTEEL', 63960.0), ('HDFCBANK', 62945.1), ('WIPRO', 53394.1), ('BANKINDIA', 53303.25)]
2006-05-01 00:00:00 [('RELIANCE', 153836.1), ('BHARTIARTL', 109559.1), ('NTPC', 83517.0), ('INFY', 73839.22), ('ICICIBANK', 70072.41), ('ITC', 58201.85), ('HDFCBANK', 57250.8), ('TATASTEEL', 51342.72), ('BANKINDIA', 50077.3), ('WIPRO', 44687.4)]
2006-06-01 00:00:00 [('RELIANCE', 170883.9), ('BHARTIARTL', 110594.4), ('NTPC', 82401.5), ('INFY', 78130.64), ('ITC', 64216.25), ('ICICIBANK', 63605.07), ('HDFCBANK', 61252.2), ('TATASTEEL', 53114.88), ('WIPRO', 51033.85), ('BANKINDIA', 44894.85)]
2006-07-01 00:00:00 [('RELIANCE', 157759.8), ('BHARTIARTL', 114492.0), ('NTPC', 85631.6), ('INFY', 84021.7), ('ICICIBANK', 72201.9), ('HDFCBANK', 61252.2), ('ITC', 58891.0), ('TATASTEEL', 49083.84), ('WIPRO', 48778.5), ('BANKINDIA', 48648.6)]
2006-08-01 00:00:00 [('RELIANCE', 180084.3), ('BHARTIARTL', 122865.75), ('NTPC', 92324.6), ('INFY', 91674.8), ('ICICIBANK', 77887.71), ('ITC', 67348.75), ('HDFCBANK', 65561.4), ('BANKINDIA', 62676.25), ('WIPRO', 51558.35), ('TATASTEEL', 49083.84)]
2006-09-01 00:00:00 [('RELIANCE', 188878.8), ('BHARTIARTL', 140252.7), ('NTPC', 96670.2), ('INFY', 93871.26), ('ICICIBANK', 91202.4), ('HDFCBANK', 71255.7), ('BANKINDIA', 71130.15), ('ITC', 66033.1), ('TATASTEEL', 53352.0), ('WIPRO', 52135.3)]
2006-10-01 00:00:00 [('RELIANCE', 197673.3), ('BHARTIARTL', 158461.8), ('INFY', 106347.64), ('ICICIBANK', 101312.1), ('NTPC', 96301.6), ('HDFCBANK', 77257.8), ('BANKINDIA', 76221.6), ('ITC', 66847.55), ('WIPRO', 53499.0), ('TATASTEEL', 48472.32)]
2006-11-01 00:00:00 [('RELIANCE', 200649.9), ('BHARTIARTL', 188515.95), ('ICICIBANK', 113737.71), ('INFY', 110618.76), ('NTPC', 109192.9), ('BANKINDIA', 88165.35), ('HDFCBANK', 86337.9), ('ITC', 65093.35), ('WIPRO', 59635.65), ('TATASTEEL', 46038.72)]
2006-12-01 00:00:00 [('RELIANCE', 204776.55), ('BHARTIARTL', 188302.8), ('ICICIBANK', 116218.53), ('INFY', 113773.38), ('NTPC', 101423.2), ('BANKINDIA', 91063.7), ('HDFCBANK', 82182.6), ('ITC', 61960.85), ('WIPRO', 60212.6), ('TATASTEEL', 47561.28)]
2007-01-01 00:00:00 [('RELIANCE', 220268.4), ('BHARTIARTL', 211992.9), ('ICICIBANK', 122685.87), ('INFY', 114053.52), ('NTPC', 105555.4), ('BANKINDIA', 83906.55), ('HDFCBANK', 82952.1), ('ITC', 61397.0), ('WIPRO', 60946.9), ('LT', 48729.18)]
2007-02-01 00:00:00 [('RELIANCE', 218035.95), ('BHARTIARTL', 214885.65), ('ICICIBANK', 108137.94), ('INFY', 105438.2), ('NTPC', 103954.9), ('HDFCBANK', 72025.2), ('BANKINDIA', 71899.1), ('ITC', 60394.6), ('WIPRO', 55859.25), ('LT', 45689.04)]
2007-03-01 00:00:00 [('BHARTIARTL', 228314.1), ('RELIANCE', 220944.9), ('NTPC', 111637.3), ('ICICIBANK', 111242.55), ('INFY', 102445.98), ('BANKINDIA', 73678.15), ('HDFCBANK', 73410.3), ('WIPRO', 55597.0), ('ITC', 53189.85), ('LT', 49682.76)]
2007-04-01 00:00:00 [('RELIANCE', 251658.0), ('BHARTIARTL', 242503.8), ('NTPC', 118737.7), ('ICICIBANK', 112877.31), ('INFY', 104082.16), ('BANKINDIA', 84475.3), ('HDFCBANK', 78796.8), ('WIPRO', 56803.35), ('ITC', 56322.35), ('TATASTEEL', 54824.64)]
2007-05-01 00:00:00 [('RELIANCE', 283521.15), ('BHARTIARTL', 253831.2), ('ICICIBANK', 119825.04), ('NTPC', 117777.4), ('INFY', 97618.64), ('BANKINDIA', 92487.85), ('HDFCBANK', 88338.6), ('TATASTEEL', 63722.88), ('LT', 61637.7), ('ITC', 57638.0)]
2007-06-01 00:00:00 [('RELIANCE', 274117.8), ('BHARTIARTL', 249872.7), ('ICICIBANK', 124557.24), ('NTPC', 113538.5), ('BANKINDIA', 101733.45), ('INFY', 97898.78), ('HDFCBANK', 88184.7), ('LT', 67406.1), ('TATASTEEL', 60003.84), ('ITC', 54442.85)]
2007-07-01 00:00:00 [('RELIANCE', 305236.8), ('BHARTIARTL', 269330.25), ('NTPC', 123199.7), ('ICICIBANK', 120907.71), ('BANKINDIA', 113413.3), ('INFY', 100273.88), ('HDFCBANK', 92340.0), ('LT', 79972.38), ('TATASTEEL', 66343.68), ('ITC', 60144.0)]
2007-08-01 00:00:00 [('RELIANCE', 316128.45), ('BHARTIARTL', 262905.3), ('NTPC', 128806.3), ('ICICIBANK', 115817.01), ('BANKINDIA', 107921.45), ('INFY', 94118.92), ('HDFCBANK', 90185.4), ('LT', 79205.1), ('TATASTEEL', 69937.92), ('ITC', 60081.35)]
2007-09-01 00:00:00 [('RELIANCE', 370451.4), ('BHARTIARTL', 280931.7), ('NTPC', 144112.9), ('ICICIBANK', 138495.72), ('BANKINDIA', 121580.55), ('HDFCBANK', 110500.2), ('INFY', 96059.6), ('TATASTEEL', 87260.16), ('LT', 86110.62), ('ITC', 66784.9)]
2007-10-01 00:00:00 [('RELIANCE', 448790.1), ('BHARTIARTL', 300846.0), ('NTPC', 177510.0), ('ICICIBANK', 163483.17), ('BANKINDIA', 156856.7), ('LT', 130127.1), ('HDFCBANK', 127275.3), ('TATASTEEL', 106104.96), ('INFY', 93250.08), ('POWERGRID', 75051.0)]
2007-11-01 00:00:00 [('RELIANCE', 459749.4), ('BHARTIARTL', 280809.9), ('NTPC', 175841.6), ('BANKINDIA', 154003.85), ('ICICIBANK', 153617.25), ('HDFCBANK', 132046.2), ('LT', 126615.0), ('TATASTEEL', 96345.6), ('INFY', 81325.86), ('POWERGRID', 74074.5)]
2007-12-01 00:00:00 [('RELIANCE', 464755.5), ('BHARTIARTL', 297801.0), ('NTPC', 186424.3), ('ICICIBANK', 161482.74), ('BANKINDIA', 160569.5), ('HDFCBANK', 132969.6), ('LT', 127800.42), ('TATASTEEL', 109699.2), ('INFY', 89823.44), ('ITC', 73676.4)]
2008-01-01 00:00:00 [('RELIANCE', 399676.2), ('BHARTIARTL', 256693.5), ('BANKINDIA', 154927.5), ('ICICIBANK', 149530.35), ('NTPC', 145674.6), ('HDFCBANK', 120811.5), ('LT', 111836.58), ('TATASTEEL', 85675.2), ('INFY', 76076.28), ('AXISBANK', 69713.76)]
2008-02-01 00:00:00 [('RELIANCE', 397105.5), ('BHARTIARTL', 246949.5), ('BANKINDIA', 157693.9), ('NTPC', 150088.1), ('ICICIBANK', 141901.47), ('HDFCBANK', 112039.2), ('LT', 107985.0), ('TATASTEEL', 93362.88), ('INFY', 78573.18), ('ITC', 71358.35)]
2008-03-01 00:00:00 [('RELIANCE', 365310.0), ('BHARTIARTL', 246949.5), ('NTPC', 146082.0), ('BANKINDIA', 111192.9), ('HDFCBANK', 102497.4), ('ICICIBANK', 100301.13), ('LT', 93101.7), ('TATASTEEL', 80308.8), ('INFY', 73075.94), ('ITC', 72611.35)]
2008-04-01 00:00:00 [('RELIANCE', 421459.5), ('BHARTIARTL', 268477.65), ('BANKINDIA', 150295.6), ('NTPC', 146198.4), ('HDFCBANK', 117271.8), ('ICICIBANK', 114669.81), ('TATASTEEL', 95372.16), ('LT', 92099.82), ('INFY', 88970.84), ('ITC', 77372.75)]
2008-05-01 00:00:00 [('RELIANCE', 387499.2), ('BHARTIARTL', 261809.1), ('BANKINDIA', 129461.15), ('NTPC', 128069.1), ('TATASTEEL', 105730.56), ('HDFCBANK', 105267.6), ('ICICIBANK', 102803.46), ('INFY', 99612.1), ('LT', 91467.78), ('ITC', 76620.95)]
2008-06-01 00:00:00 [('RELIANCE', 337776.45), ('BHARTIARTL', 215555.55), ('NTPC', 112869.2), ('BANKINDIA', 95322.5), ('INFY', 88142.6), ('TATASTEEL', 84514.56), ('ICICIBANK', 82153.86), ('HDFCBANK', 77565.6), ('LT', 66997.62), ('ITC', 66095.75)]
2008-07-01 00:00:00 [('RELIANCE', 355839.0), ('BHARTIARTL', 238728.0), ('NTPC', 126575.3), ('BANKINDIA', 119692.3), ('HDFCBANK', 84491.1), ('ICICIBANK', 83078.79), ('INFY', 80359.58), ('LT', 79903.38), ('TATASTEEL', 75491.52), ('ITC', 65719.85)]
2008-08-01 00:00:00 [('RELIANCE', 344338.5), ('BHARTIARTL', 250329.45), ('NTPC', 129960.6), ('BANKINDIA', 117494.65), ('HDFCBANK', 98188.2), ('INFY', 88767.84), ('ICICIBANK', 87588.72), ('LT', 79541.82), ('TATASTEEL', 68839.68), ('ITC', 66409.0)]
2008-09-01 00:00:00 [('RELIANCE', 314301.9), ('BHARTIARTL', 234586.8), ('NTPC', 127729.6), ('BANKINDIA', 125243.3), ('HDFCBANK', 94648.5), ('LT', 75023.7), ('INFY', 70952.56), ('ICICIBANK', 69814.29), ('ITC', 66158.4), ('TATASTEEL', 47686.08)]
2008-10-01 00:00:00 [('RELIANCE', 221756.7), ('BHARTIARTL', 195397.65), ('BANKINDIA', 105728.35), ('NTPC', 104837.6), ('HDFCBANK', 78642.9), ('INFY', 70489.72), ('ITC', 54630.8), ('ICICIBANK', 51982.5), ('LT', 49499.22), ('AXISBANK', 35015.49)]
2008-11-01 00:00:00 [('BHARTIARTL', 200574.15), ('RELIANCE', 182925.6), ('NTPC', 118475.8), ('BANKINDIA', 110096.35), ('HDFCBANK', 70947.9), ('INFY', 63124.88), ('ITC', 61083.75), ('ICICIBANK', 45844.98), ('LT', 44604.36), ('POWERGRID', 35433.0)]
2008-12-01 00:00:00 [('BHARTIARTL', 213850.35), ('RELIANCE', 198755.7), ('NTPC', 134189.8), ('BANKINDIA', 126035.0), ('HDFCBANK', 76796.1), ('ITC', 60394.6), ('ICICIBANK', 58413.99), ('INFY', 56608.58), ('LT', 47456.82), ('POWERGRID', 40176.0)]
2009-01-01 00:00:00 [('RELIANCE', 213368.1), ('BHARTIARTL', 189490.35), ('NTPC', 140921.6), ('BANKINDIA', 109436.6), ('HDFCBANK', 71255.7), ('INFY', 66311.98), ('ITC', 63401.8), ('ICICIBANK', 54262.56), ('POWERGRID', 42873.0), ('LT', 42335.64)]
2009-02-01 00:00:00 [('RELIANCE', 204100.05), ('BHARTIARTL', 190830.15), ('NTPC', 137468.4), ('BANKINDIA', 99030.75), ('HDFCBANK', 68485.5), ('ITC', 64404.2), ('INFY', 62487.46), ('POWERGRID', 47383.5), ('ICICIBANK', 42697.35), ('LT', 37643.64)]
2009-03-01 00:00:00 [('RELIANCE', 245840.1), ('BHARTIARTL', 187023.9), ('NTPC', 133636.9), ('BANKINDIA', 96332.6), ('HDFCBANK', 74949.3), ('INFY', 67188.94), ('ITC', 65030.7), ('POWERGRID', 46686.0), ('ICICIBANK', 43385.67), ('LT', 41179.2)]
2009-04-01 00:00:00 [('RELIANCE', 291165.6), ('BHARTIARTL', 224995.05), ('NTPC', 141173.8), ('BANKINDIA', 103225.85), ('HDFCBANK', 84645.0), ('INFY', 76595.96), ('ITC', 66471.65), ('ICICIBANK', 62472.21), ('LT', 53933.16), ('POWERGRID', 45151.5)]
2009-05-01 00:00:00 [('RELIANCE', 366257.1), ('BHARTIARTL', 245366.1), ('NTPC', 160050.0), ('BANKINDIA', 148184.4), ('HDFCBANK', 111115.8), ('ICICIBANK', 96486.69), ('LT', 86001.6), ('INFY', 81459.84), ('ITC', 64592.15), ('POWERGRID', 56823.0)]

In [ ]:
# Obtain price data for universe securities using history and print it

if not universe_symbols:
    raise RuntimeError("Universe symbols are empty. Run Cell 6 first.")

# Rebind custom data loader to Postgres session used by universe builder.
db_tick_custom_data.SessionLocal = db_universe_custom_data.build_session_local()
DbDailyByTradingsymbol._prepared_symbols = set()

lookback_bars = 60
max_symbols = 20  # keep output manageable
symbols_to_query = universe_symbols[:max_symbols]

print(f"Fetching {lookback_bars} daily bars for {len(symbols_to_query)} securities...")

for symbol in symbols_to_query:
    try:
        raw_hist = qb.history(symbol, lookback_bars, Resolution.DAILY)
        display(raw_hist.head())
    except Exception:
        continue

Fetching 60 daily bars for 10 securities...
[DbDailyByTradingsymbol] Refreshing cache for RELIANCE
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=RELIANCE
[DbDailyByTradingsymbol] Resolved instrument_token=738561
[DbDailyByTradingsymbol] Fetched 6217 rows from daily_candles, date range [2001-04-20 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1331.0/11593905 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/RELIANCE.csv
Raw history for RELIANCE.DbDailyByTradingsymbol:
                                               close     high      low  \
symbol                          time
RELIANCE.DbDailyByTradingsymbol 2024-02-02  1457.70  1474.90  1433.20
                                2024-02-05  1439.00  1470.50  1431.50
                                2024-02-06  1427.80  1441.85  1419.80
                                2024-02-07  1442.15  1449.50  1429.25
                                2024-02-08  1450.10  1459.50  1427.50

                                               open    value      volume
symbol                          time
RELIANCE.DbDailyByTradingsymbol 2024-02-02  1433.20  1457.70  19652588.0
                                2024-02-05  1460.75  1439.00   8814432.0
                                2024-02-06  1441.85  1427.80   9047984.0
                                2024-02-07  1435.90  1442.15   9296568.0
                                2024-02-08  1450.00  1450.10  14694634.0

                                              close     high      low  \
symbol                          time
RELIANCE.DbDailyByTradingsymbol 2024-02-02  1457.70  1474.90  1433.20
                                2024-02-05  1439.00  1470.50  1431.50
                                2024-02-06  1427.80  1441.85  1419.80
                                2024-02-07  1442.15  1449.50  1429.25
                                2024-02-08  1450.10  1459.50  1427.50

                                               open    value      volume
symbol                          time
RELIANCE.DbDailyByTradingsymbol 2024-02-02  1433.20  1457.70  19652588.0
                                2024-02-05  1460.75  1439.00   8814432.0
                                2024-02-06  1441.85  1427.80   9047984.0
                                2024-02-07  1435.90  1442.15   9296568.0
                                2024-02-08  1450.00  1450.10  14694634.0

[DbDailyByTradingsymbol] Refreshing cache for HDFCBANK
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=HDFCBANK
[DbDailyByTradingsymbol] Resolved instrument_token=341249
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 785.15/26155682 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/HDFCBANK.csv
Raw history for HDFCBANK.DbDailyByTradingsymbol:
                                             close   high    low   open  value  \
symbol                          time
HDFCBANK.DbDailyByTradingsymbol 2024-02-02  723.1  740.4  721.0  737.5  723.1
                                2024-02-05  722.4  726.0  717.0  723.0  722.4
                                2024-02-06  722.0  724.8  716.3  722.8  722.0
                                2024-02-07  715.0  726.9  713.3  726.5  715.0
                                2024-02-08  701.5  719.5  700.2  714.9  701.5

                                                volume
symbol                          time
HDFCBANK.DbDailyByTradingsymbol 2024-02-02  44867754.0
                                2024-02-05  38605046.0
                                2024-02-06  41075740.0
                                2024-02-07  54837086.0
                                2024-02-08  69106124.0

                                            close   high    low   open  value  \
symbol                          time
HDFCBANK.DbDailyByTradingsymbol 2024-02-02  723.1  740.4  721.0  737.5  723.1
                                2024-02-05  722.4  726.0  717.0  723.0  722.4
                                2024-02-06  722.0  724.8  716.3  722.8  722.0
                                2024-02-07  715.0  726.9  713.3  726.5  715.0
                                2024-02-08  701.5  719.5  700.2  714.9  701.5

                                                volume
symbol                          time
HDFCBANK.DbDailyByTradingsymbol 2024-02-02  44867754.0
                                2024-02-05  38605046.0
                                2024-02-06  41075740.0
                                2024-02-07  54837086.0
                                2024-02-08  69106124.0

[DbDailyByTradingsymbol] Refreshing cache for BHARTIARTL
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=BHARTIARTL
[DbDailyByTradingsymbol] Resolved instrument_token=2714625
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1817.0/6220105 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/BHARTIARTL.csv
Raw history for BHARTIARTL.DbDailyByTradingsymbol:
                                                 close     high     low  \
symbol                            time
BHARTIARTL.DbDailyByTradingsymbol 2024-02-02  1150.80  1175.20  1145.3
                                  2024-02-05  1113.55  1159.65  1110.0
                                  2024-02-06  1134.05  1156.10  1123.0
                                  2024-02-07  1134.30  1148.25  1131.8
                                  2024-02-08  1142.15  1146.50  1116.2

                                                 open    value     volume
symbol                            time
BHARTIARTL.DbDailyByTradingsymbol 2024-02-02  1155.00  1150.80  4969983.0
                                  2024-02-05  1154.35  1113.55  7809331.0
                                  2024-02-06  1125.00  1134.05  9863065.0
                                  2024-02-07  1138.80  1134.30  2770694.0
                                  2024-02-08  1144.40  1142.15  6519392.0

                                                close     high     low  \
symbol                            time
BHARTIARTL.DbDailyByTradingsymbol 2024-02-02  1150.80  1175.20  1145.3
                                  2024-02-05  1113.55  1159.65  1110.0
                                  2024-02-06  1134.05  1156.10  1123.0
                                  2024-02-07  1134.30  1148.25  1131.8
                                  2024-02-08  1142.15  1146.50  1116.2

                                                 open    value     volume
symbol                            time
BHARTIARTL.DbDailyByTradingsymbol 2024-02-02  1155.00  1150.80  4969983.0
                                  2024-02-05  1154.35  1113.55  7809331.0
                                  2024-02-06  1125.00  1134.05  9863065.0
                                  2024-02-07  1138.80  1134.30  2770694.0
                                  2024-02-08  1144.40  1142.15  6519392.0

[DbDailyByTradingsymbol] Refreshing cache for ICICIBANK
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=ICICIBANK
[DbDailyByTradingsymbol] Resolved instrument_token=1270529
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1325.7/13859364 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/ICICIBANK.csv
Raw history for ICICIBANK.DbDailyByTradingsymbol:
                                                close     high      low  \
symbol                           time
ICICIBANK.DbDailyByTradingsymbol 2024-02-02  1024.00  1050.00  1021.65
                                 2024-02-05  1023.50  1026.45  1012.10
                                 2024-02-06  1026.40  1034.90  1016.70
                                 2024-02-07  1022.15  1031.55  1013.00
                                 2024-02-08   989.30  1028.25   985.25

                                                open    value      volume
symbol                           time
ICICIBANK.DbDailyByTradingsymbol 2024-02-02  1037.10  1024.00  14774650.0
                                 2024-02-05  1022.50  1023.50  12948430.0
                                 2024-02-06  1023.55  1026.40  12886927.0
                                 2024-02-07  1028.00  1022.15  16410895.0
                                 2024-02-08  1024.10   989.30  20565502.0

                                               close     high      low  \
symbol                           time
ICICIBANK.DbDailyByTradingsymbol 2024-02-02  1024.00  1050.00  1021.65
                                 2024-02-05  1023.50  1026.45  1012.10
                                 2024-02-06  1026.40  1034.90  1016.70
                                 2024-02-07  1022.15  1031.55  1013.00
                                 2024-02-08   989.30  1028.25   985.25

                                                open    value      volume
symbol                           time
ICICIBANK.DbDailyByTradingsymbol 2024-02-02  1037.10  1024.00  14774650.0
                                 2024-02-05  1022.50  1023.50  12948430.0
                                 2024-02-06  1023.55  1026.40  12886927.0
                                 2024-02-07  1028.00  1022.15  16410895.0
                                 2024-02-08  1024.10   989.30  20565502.0

[DbDailyByTradingsymbol] Refreshing cache for BAJFINANCE
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=BAJFINANCE
[DbDailyByTradingsymbol] Resolved instrument_token=81153
[DbDailyByTradingsymbol] Fetched 5729 rows from daily_candles, date range [2003-01-27 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 923.0/3967084 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/BAJFINANCE.csv
Raw history for BAJFINANCE.DbDailyByTradingsymbol:
                                               close   high    low   open  \
symbol                            time
BAJFINANCE.DbDailyByTradingsymbol 2024-02-02  685.0  691.0  675.0  675.5
                                  2024-02-05  661.0  689.5  660.0  689.5
                                  2024-02-06  660.0  670.0  653.5  665.0
                                  2024-02-07  671.0  674.0  662.5  664.0
                                  2024-02-08  657.5  674.0  654.0  673.0

                                              value      volume
symbol                            time
BAJFINANCE.DbDailyByTradingsymbol 2024-02-02  685.0  13675080.0
                                  2024-02-05  661.0  17712220.0
                                  2024-02-06  660.0  24395330.0
                                  2024-02-07  671.0  15382370.0
                                  2024-02-08  657.5  21932090.0

                                              close   high    low   open  \
symbol                            time
BAJFINANCE.DbDailyByTradingsymbol 2024-02-02  685.0  691.0  675.0  675.5
                                  2024-02-05  661.0  689.5  660.0  689.5
                                  2024-02-06  660.0  670.0  653.5  665.0
                                  2024-02-07  671.0  674.0  662.5  664.0
                                  2024-02-08  657.5  674.0  654.0  673.0

                                              value      volume
symbol                            time
BAJFINANCE.DbDailyByTradingsymbol 2024-02-02  685.0  13675080.0
                                  2024-02-05  661.0  17712220.0
                                  2024-02-06  660.0  24395330.0
                                  2024-02-07  671.0  15382370.0
                                  2024-02-08  657.5  21932090.0

[DbDailyByTradingsymbol] Refreshing cache for LT
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=LT
[DbDailyByTradingsymbol] Resolved instrument_token=2939649
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 4012.0/2155271 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/LT.csv
Raw history for LT.DbDailyByTradingsymbol:
                                         close     high      low    open  \
symbol                    time
LT.DbDailyByTradingsymbol 2024-02-02  3376.05  3436.35  3361.00  3402.7
                          2024-02-05  3341.75  3407.95  3318.45  3375.5
                          2024-02-06  3424.25  3427.75  3337.55  3346.0
                          2024-02-07  3394.70  3447.00  3389.00  3445.0
                          2024-02-08  3335.50  3417.80  3293.85  3413.0

                                        value     volume
symbol                    time
LT.DbDailyByTradingsymbol 2024-02-02  3376.05  7579802.0
                          2024-02-05  3341.75  2954238.0
                          2024-02-06  3424.25  2545192.0
                          2024-02-07  3394.70  2099940.0
                          2024-02-08  3335.50  3471727.0

                                        close     high      low    open  \
symbol                    time
LT.DbDailyByTradingsymbol 2024-02-02  3376.05  3436.35  3361.00  3402.7
                          2024-02-05  3341.75  3407.95  3318.45  3375.5
                          2024-02-06  3424.25  3427.75  3337.55  3346.0
                          2024-02-07  3394.70  3447.00  3389.00  3445.0
                          2024-02-08  3335.50  3417.80  3293.85  3413.0

                                        value     volume
symbol                    time
LT.DbDailyByTradingsymbol 2024-02-02  3376.05  7579802.0
                          2024-02-05  3341.75  2954238.0
                          2024-02-06  3424.25  2545192.0
                          2024-02-07  3394.70  2099940.0
                          2024-02-08  3335.50  3471727.0

[DbDailyByTradingsymbol] Refreshing cache for INFY
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=INFY
[DbDailyByTradingsymbol] Resolved instrument_token=408065
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1154.8/41354744 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/INFY.csv
Raw history for INFY.DbDailyByTradingsymbol:
                                           close     high      low     open  \
symbol                      time
INFY.DbDailyByTradingsymbol 2024-02-02  1693.35  1718.50  1665.00  1666.05
                            2024-02-05  1687.20  1700.75  1681.85  1694.75
                            2024-02-06  1729.45  1733.00  1673.95  1686.75
                            2024-02-07  1693.75  1729.00  1686.85  1729.00
                            2024-02-08  1692.10  1706.35  1682.80  1698.00

                                          value     volume
symbol                      time
INFY.DbDailyByTradingsymbol 2024-02-02  1693.35  7858483.0
                            2024-02-05  1687.20  3634135.0
                            2024-02-06  1729.45  7694265.0
                            2024-02-07  1693.75  4613877.0
                            2024-02-08  1692.10  5919715.0

                                          close     high      low     open  \
symbol                      time
INFY.DbDailyByTradingsymbol 2024-02-02  1693.35  1718.50  1665.00  1666.05
                            2024-02-05  1687.20  1700.75  1681.85  1694.75
                            2024-02-06  1729.45  1733.00  1673.95  1686.75
                            2024-02-07  1693.75  1729.00  1686.85  1729.00
                            2024-02-08  1692.10  1706.35  1682.80  1698.00

                                          value     volume
symbol                      time
INFY.DbDailyByTradingsymbol 2024-02-02  1693.35  7858483.0
                            2024-02-05  1687.20  3634135.0
                            2024-02-06  1729.45  7694265.0
                            2024-02-07  1693.75  4613877.0
                            2024-02-08  1692.10  5919715.0

[DbDailyByTradingsymbol] Refreshing cache for AXISBANK
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=AXISBANK
[DbDailyByTradingsymbol] Resolved instrument_token=1510401
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 1362.0/3633490 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/AXISBANK.csv
Raw history for AXISBANK.DbDailyByTradingsymbol:
                                               close    high      low     open  \
symbol                          time
AXISBANK.DbDailyByTradingsymbol 2024-02-02  1067.05  1096.2  1065.00  1088.05
                                2024-02-05  1061.50  1079.5  1058.00  1067.05
                                2024-02-06  1050.05  1065.1  1048.20  1061.55
                                2024-02-07  1069.10  1073.7  1057.50  1061.05
                                2024-02-08  1035.90  1075.6  1031.65  1072.00

                                              value      volume
symbol                          time
AXISBANK.DbDailyByTradingsymbol 2024-02-02  1067.05   8667415.0
                                2024-02-05  1061.50  12569454.0
                                2024-02-06  1050.05   8011171.0
                                2024-02-07  1069.10   7281793.0
                                2024-02-08  1035.90   9869141.0

                                              close    high      low     open  \
symbol                          time
AXISBANK.DbDailyByTradingsymbol 2024-02-02  1067.05  1096.2  1065.00  1088.05
                                2024-02-05  1061.50  1079.5  1058.00  1067.05
                                2024-02-06  1050.05  1065.1  1048.20  1061.55
                                2024-02-07  1069.10  1073.7  1057.50  1061.05
                                2024-02-08  1035.90  1075.6  1031.65  1072.00

                                              value      volume
symbol                          time
AXISBANK.DbDailyByTradingsymbol 2024-02-02  1067.05   8667415.0
                                2024-02-05  1061.50  12569454.0
                                2024-02-06  1050.05   8011171.0
                                2024-02-07  1069.10   7281793.0
                                2024-02-08  1035.90   9869141.0

[DbDailyByTradingsymbol] Refreshing cache for MARUTI
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=MARUTI
[DbDailyByTradingsymbol] Resolved instrument_token=2815745
[DbDailyByTradingsymbol] Fetched 5618 rows from daily_candles, date range [2003-07-09 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 13060.0/463475 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/MARUTI.csv
Raw history for MARUTI.DbDailyByTradingsymbol:
                                              close      high       low  \
symbol                        time
MARUTI.DbDailyByTradingsymbol 2024-02-02  10655.45  10711.60  10540.40
                              2024-02-05  10428.55  10759.95  10400.00
                              2024-02-06  10844.85  10856.75  10458.00
                              2024-02-07  10935.70  10973.50  10786.80
                              2024-02-08  10743.90  10951.00  10689.95

                                              open     value    volume
symbol                        time
MARUTI.DbDailyByTradingsymbol 2024-02-02  10598.00  10655.45  814940.0
                              2024-02-05  10602.00  10428.55  365105.0
                              2024-02-06  10499.95  10844.85  829040.0
                              2024-02-07  10860.00  10935.70  560808.0
                              2024-02-08  10951.00  10743.90  557082.0

                                             close      high       low  \
symbol                        time
MARUTI.DbDailyByTradingsymbol 2024-02-02  10655.45  10711.60  10540.40
                              2024-02-05  10428.55  10759.95  10400.00
                              2024-02-06  10844.85  10856.75  10458.00
                              2024-02-07  10935.70  10973.50  10786.80
                              2024-02-08  10743.90  10951.00  10689.95

                                              open     value    volume
symbol                        time
MARUTI.DbDailyByTradingsymbol 2024-02-02  10598.00  10655.45  814940.0
                              2024-02-05  10602.00  10428.55  365105.0
                              2024-02-06  10499.95  10844.85  829040.0
                              2024-02-07  10860.00  10935.70  560808.0
                              2024-02-08  10951.00  10743.90  557082.0

[DbDailyByTradingsymbol] Refreshing cache for TITAN
[DbDailyByTradingsymbol] Resolving instrument for tradingsymbol=TITAN
[DbDailyByTradingsymbol] Resolved instrument_token=897537
[DbDailyByTradingsymbol] Fetched 5747 rows from daily_candles, date range [2003-01-01 -> 2026-04-24]
[DbDailyByTradingsymbol] Latest row close/volume = 4416.0/956942 on 2026-04-24
[DbDailyByTradingsymbol] Wrote cache file: /tmp/lean-db-daily/TITAN.csv
Raw history for TITAN.DbDailyByTradingsymbol:
                                            close     high      low     open  \
symbol                       time
TITAN.DbDailyByTradingsymbol 2024-02-02  3612.40  3713.45  3602.45  3635.00
                             2024-02-05  3552.05  3624.65  3534.90  3612.95
                             2024-02-06  3559.15  3577.95  3531.60  3552.05
                             2024-02-07  3576.50  3620.00  3555.80  3578.00
                             2024-02-08  3549.10  3610.00  3503.00  3604.80

                                           value     volume
symbol                       time
TITAN.DbDailyByTradingsymbol 2024-02-02  3612.40  2320153.0
                             2024-02-05  3552.05  1771614.0
                             2024-02-06  3559.15  1069901.0
                             2024-02-07  3576.50   900220.0
                             2024-02-08  3549.10  1011857.0

                                           close     high      low     open  \
symbol                       time
TITAN.DbDailyByTradingsymbol 2024-02-02  3612.40  3713.45  3602.45  3635.00
                             2024-02-05  3552.05  3624.65  3534.90  3612.95
                             2024-02-06  3559.15  3577.95  3531.60  3552.05
                             2024-02-07  3576.50  3620.00  3555.80  3578.00
                             2024-02-08  3549.10  3610.00  3503.00  3604.80

                                           value     volume
symbol                       time
TITAN.DbDailyByTradingsymbol 2024-02-02  3612.40  2320153.0
                             2024-02-05  3552.05  1771614.0
                             2024-02-06  3559.15  1069901.0
                             2024-02-07  3576.50   900220.0
                             2024-02-08  3549.10  1011857.0